- hosts: all
  become: yes
  tasks:
    - name: create the 'ansi' user
      user: name=ansi append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ansi' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ansi ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=ansi key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
